In [1]:
import numpy as np
import time

In [7]:
x = np.random.random(1000000)
start = time.time()
print(sum(x)/len(x))
print(time.time() - start)

0.5002619288635182
0.3717331886291504


In [8]:
start = time.time()
np.mean(x)
print(time.time()-start)

0.008081197738647461


In [10]:
# Create 1D array
x = np.array([1,2,3,6])
print(x,type(x),x.dtype)

[1 2 3 6] <class 'numpy.ndarray'> int32


In [15]:
# Create 2d array
y = np.array([[1,2,3],[4,5,6]])
print(y,y.shape,type(y),y.ndim)

[[1 2 3]
 [4 5 6]] (2, 3) <class 'numpy.ndarray'> 2


In [25]:
z = np.array([21,3,4],dtype='complex')
np.save("my_array",z)

In [26]:
np.load("my_array.npy")

array([21.+0.j,  3.+0.j,  4.+0.j])

In [28]:
i = np.zeros((3,4),dtype='int')
i

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [33]:
j = np.ones((2,2))
j

array([[1., 1.],
       [1., 1.]])

In [36]:
k = np.full((4,4),5,dtype='int')
k

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [38]:
m = np.eye(5,dtype='int')
m

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [39]:
n = np.diag([10,20,30,40])# diagonal elements only
n

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

In [41]:
e = np.arange(2,22,4)
e

array([ 2,  6, 10, 14, 18])

In [52]:
f = np.linspace(2,18,5,dtype=int)
f

array([ 2,  6, 10, 14, 18])

In [53]:
x = np.linspace(0,25,10)

In [54]:
x

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [55]:
x = np.linspace(0,25,10,endpoint=False)

In [56]:
x


array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5])

In [62]:
x =  np.reshape(x,(2,5))
x

array([[ 0. ,  2.5,  5. ,  7.5, 10. ],
       [12.5, 15. , 17.5, 20. , 22.5]])

In [66]:
x = np.linspace(0,100,20,endpoint=False,dtype='int').reshape(10,2)
x

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35],
       [40, 45],
       [50, 55],
       [60, 65],
       [70, 75],
       [80, 85],
       [90, 95]])

In [69]:
x = np.random.random((2,2))
x

array([[0.9296525 , 0.17213476],
       [0.82437422, 0.1351627 ]])

In [70]:
x = np.random.randint(4,15,(3,2))

In [71]:
x

array([[12,  9],
       [11,  8],
       [10, 11]])

In [72]:
x = np.random.normal(0,0.1,size=(100,1000))

In [81]:
x.shape

print(x.mean())
print(x.std())
print(x.max())
print(x.min())

-0.00030861603869681734
0.09987936144676446
0.45427166156897275
-0.4655153760961341
